[package]
name = "xmithd_backend"
version = "1.0.0"
authors = ["Amit Dayaram <amit.hotchandanidayaram@mcgill.ca>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.7"
actix-web = "1.0"
actix-files = "0.1"
serde = "1.0"
serde_json = "1.0"
handlebars = "2.0"
serde_derive = "1.0"
